#!/usr/bin/env python3
"""build_adjacency_map.py - Region adjacency per trading bloc from REAL admin boundaries.

Uses each region's study-area shapefile (generated by batch_countries.py from Natural
Earth Admin-1 boundaries). Adjacency = polygons share a border (land) OR shortest
inter-polygon distance < ADJ_SEA_KM (sea crossing, e.g. UK<->continent, island chains).
This replaces the centroid K-nearest heuristic used in the E skeleton, fixing the
"California <-> East Coast" and "cross-ocean" spurious links.

Outputs (E_output/adjacency/): adjacency_<bloc>.csv + adjacency_<bloc>.png per bloc.

Run:  ADJ_SEA_KM=300 python3 build_adjacency_map.py
"""
import os
import glob
import warnings
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')

ADJ_SEA_KM = float(os.environ.get('ADJ_SEA_KM', '300'))   # max sea-crossing distance for adjacency
LAND_KM = float(os.environ.get('ADJ_LAND_KM', '8'))       # <= this = shared land border
OUT_DIR = '/home/cfeng/myswat/REVUB/1_REVUB_code/E_output/adjacency'
os.makedirs(OUT_DIR, exist_ok=True)

TRADING_BLOCS = {
    'china': ['china_cc', 'china_csg', 'china_ec', 'china_nc', 'china_ne', 'china_nw', 'china_sw', 'hong_kong'],
    'india': ['india_east', 'india_north', 'india_northeast', 'india_south', 'india_west'],
    'southeast_asia': ['cambodia', 'indonesia', 'laos', 'malaysia_east', 'malaysia_west',
                       'myanmar', 'philippines', 'thailand', 'vietnam', 'singapore'],
    'south_america': ['argentina', 'bolivia', 'chile', 'colombia', 'ecuador', 'peru',
                      'brazil_nordeste', 'brazil_norte', 'brazil_sudeste', 'brazil_sul'],
    'europe': ['austria', 'germany', 'hungary', 'poland', 'slovakia', 'slovenia', 'switzerland', 'turkey',
               'latvia', 'lithuania', 'finland', 'norway', 'sweden',
               'albania', 'bulgaria', 'croatia', 'greece', 'italy', 'north_macedonia', 'portugal',
               'romania', 'serbia', 'spain',
               'belgium', 'france', 'ireland', 'luxembourg', 'united_kingdom',
               'denmark', 'netherlands', 'czechia', 'estonia'],
    'north_america': ['usa_caiso', 'usa_ercot', 'usa_isone', 'usa_miso_central', 'usa_miso_north',
                      'usa_miso_south', 'usa_northerngrid_east', 'usa_northerngrid_south',
                      'usa_northerngrid_west', 'usa_nyiso', 'usa_pjm_east', 'usa_pjm_west', 'usa_sertp',
                      'usa_spp_north', 'usa_spp_south', 'usa_westconnect_north', 'usa_westconnect_south',
                      'canada_atlantic', 'canada_bc', 'canada_ontario', 'canada_prairies', 'canada_quebec', 'usa_frcc'],
}


def find_shp(r):
    # BEFORE-expansion boundary: admin (china/india/brazil), target (europe), ba (usa).
    # Explicitly NOT _study_area_expanded.shp nor vectors/study_area.shp (those are the
    # river upstream/downstream EXPANDED versions, which deform the administrative outline).
    for suffix in ('_study_area_admin.shp', '_study_area_target.shp', '_study_area_ba.shp'):
        for root in ('/datasets/swat_global', '/home/cfeng/myswat/swat_global'):
            c = glob.glob(f'{root}/*/{r}/{suffix}')
            if c:
                return c[0]
    # Fallback for DC-only regions (hong_kong, singapore, denmark, netherlands, czechia):
    # they have NO hydro -> no river expansion was ever applied, so vectors/study_area.shp
    # IS their unexpanded administrative outline (nothing to expand). Safe here because
    # any hydro region already matched admin/target/ba above and never reaches this line.
    for root in ('/datasets/swat_global', '/home/cfeng/myswat/swat_global'):
        c = glob.glob(f'{root}/*/{r}/vectors/study_area.shp')
        if c:
            return c[0]
    return None


def build_bloc(bloc, regions):
    geoms = {}
    for r in regions:
        shp = find_shp(r)
        if shp is None:
            print(f'    [skip] {r}: no shapefile')
            continue
        try:
            g = gpd.read_file(shp).to_crs('EPSG:4326')
            geoms[r] = g.geometry.union_all() if hasattr(g.geometry, 'union_all') else g.geometry.unary_union
        except Exception as e:
            print(f'    [err] {r}: {e}')
    if len(geoms) < 2:
        return None
    regs = list(geoms)
    gdf = gpd.GeoDataFrame({'region': regs}, geometry=[geoms[r] for r in regs], crs='EPSG:4326')
    gdf_eq = gdf.to_crs('EPSG:4087')   # World Equidistant Cylindrical -> distances in meters
    gdf_eq['geometry'] = gdf_eq.geometry.simplify(2000)  # 2km tolerance -> much faster distance matrix

    adj = {r: [] for r in regs}
    edges = []
    for i in range(len(regs)):
        for j in range(i + 1, len(regs)):
            d_km = gdf_eq.geometry.iloc[i].distance(gdf_eq.geometry.iloc[j]) / 1000.0
            if d_km <= ADJ_SEA_KM:
                kind = 'land' if d_km <= LAND_KM else 'sea'
                adj[regs[i]].append((regs[j], d_km, kind))
                adj[regs[j]].append((regs[i], d_km, kind))
                edges.append((regs[i], regs[j], d_km, kind))
    return gdf, adj, edges


for bloc, regions in TRADING_BLOCS.items():
    print(f'\n=== {bloc} ===')
    res = build_bloc(bloc, regions)
    if res is None:
        print('   <2 regions with shapefiles, skipped')
        continue
    gdf, adj, edges = res
    cent = {row.region: (row.geometry.centroid.x, row.geometry.centroid.y) for _, row in gdf.iterrows()}

    fig, ax = plt.subplots(figsize=(13, 10))
    gdf.plot(ax=ax, facecolor='#EAEAEA', edgecolor='#888888', linewidth=0.4)
    n_land = n_sea = 0
    for r1, r2, d, kind in edges:
        x = [cent[r1][0], cent[r2][0]]; y = [cent[r1][1], cent[r2][1]]
        if kind == 'land':
            ax.plot(x, y, color='#2E7D32', lw=1.6, alpha=0.8, zorder=2); n_land += 1
        else:
            ax.plot(x, y, color='#EF6C00', lw=0.9, ls='--', alpha=0.7, zorder=2); n_sea += 1
    for r, (x, y) in cent.items():
        ax.plot(x, y, 'o', color='#C62828', ms=4, zorder=3)
        ax.annotate(r.replace(f'{bloc}_', '').replace('usa_', '').replace('canada_', 'ca_'),
                    (x, y), fontsize=6.5, zorder=4)
    ax.set_title(f'{bloc}: region adjacency  (green=shared border, orange dashed=sea <{ADJ_SEA_KM:.0f}km)\n'
                 f'{len(gdf)} regions, {n_land} land + {n_sea} sea edges', fontsize=11)
    ax.set_xlabel('lon'); ax.set_ylabel('lat')
    plt.tight_layout()
    png = os.path.join(OUT_DIR, f'adjacency_{bloc}.png')
    plt.savefig(png, dpi=120, bbox_inches='tight'); plt.close(fig)

    rows = [{'region': r, 'neighbor': n, 'dist_km': round(d, 1), 'kind': k}
            for r in adj for n, d, k in sorted(adj[r], key=lambda x: x[1])]
    pd.DataFrame(rows).to_csv(os.path.join(OUT_DIR, f'adjacency_{bloc}.csv'), index=False)
    print(f'   {len(gdf)} regions, {n_land} land + {n_sea} sea edges -> {png}')
    # quick text view of each region's neighbors
    for r in sorted(adj):
        nb = ', '.join(f'{n}({d:.0f}km,{k})' for n, d, k in sorted(adj[r], key=lambda x: x[1]))
        print(f'     {r:24s} -> {nb if nb else "(ISOLATED)"}')

print(f'\nSaved adjacency maps + tables to {OUT_DIR}/')
